In [1]:
import pandas as pd
import numpy as np
from folktables import ACSDataSource, ACSEmployment, ACSIncomePovertyRatio, ACSMobility, ACSIncome, ACSHealthInsurance, ACSPublicCoverage, ACSTravelTime, generate_categories
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
import os

In [2]:
path = '/home/lvu5/temp-fair/superhumn-fairness/dataset/Adult/A_test.csv'

In [10]:
path = '/home/lvu5/temp-fair/superhumn-fairness/experiments/test/test_data_acs_west_income_MFOpt_0-01_50_0-0.csv'

In [13]:
df = pd.read_csv(path, index_col=0)

In [14]:
df

,AGEP,WKHP,COW_1.0,COW_2.0,COW_3.0,COW_4.0,COW_5.0,COW_6.0,COW_7.0,COW_8.0,...,RELP_14.0,RELP_15.0,RELP_16.0,RELP_17.0,SEX_1.0,SEX_2.0,RAC1P_1.0,RAC1P_2.0,RAC1P,PINCP
0,0.410456,-1.666298,0,0,0,0,0,1,0,0,...,0,0,0,0,1,0,1,0,0,0
1,-1.096848,0.526027,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
2,0.082781,0.526027,0,0,0,0,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0
3,1.196875,0.148040,0,0,0,0,0,1,0,0,...,0,0,0,0,0,1,1,0,0,0
4,0.803665,0.904014,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109957,0.410456,0.148040,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
109958,-0.048289,0.148040,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
109959,-0.572569,1.659988,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,1
109960,0.082781,0.904014,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,1,0,0,0
109961,0.017246,0.148040,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0

In [6]:
df.reset_index()

        level_0   index  Unnamed: 0  RAC1P
0             0       0           0      0
1             1       1           1      0
2             2       2           2      0
3             3       3           3      0
4             4       4           4      0
...         ...     ...         ...    ...
192635   192635  192635      192635      0
192636   192636  192636      192636      0
192637   192637  192637      192637      0
192638   192638  192638      192638      0
192639   192639  192639      192639      1

[192640 rows x 4 columns]

In [5]:
df

         index  Unnamed: 0  RAC1P
0            0           0      0
1            1           1      0
2            2           2      0
3            3           3      0
4            4           4      0
...        ...         ...    ...
192635  192635      192635      0
192636  192636      192636      0
192637  192637      192637      0
192638  192638      192638      0
192639  192639      192639      1

[192640 rows x 3 columns]

In [52]:
data_source = ACSDataSource(
    survey_year='2018', horizon='1-Year', survey='person')

west_states = ["CA", "OR", "WA", "NV", "AZ"]
east_states = ['ME', 'NH', 'MA', 'RI', 'CT', 'NY',
                'NJ', 'DE', 'MD', 'VA', 'NC', 'SC', 'GA', 'FL']
acs_data = data_source.get_data(states=west_states, download=True)

acss = ['acs_west_poverty', 'acs_west_mobility', 'acs_west_income', 'acs_west_insurance',
        'acs_west_public', 'acs_west_travel', 'acs_west_poverty', 'acs_west_employment']
param = [128, 4, 8, 16, 32, 64, 128, 256]
folks = [ACSIncomePovertyRatio, ACSMobility, ACSIncome, ACSHealthInsurance,
            ACSPublicCoverage, ACSTravelTime, ACSIncomePovertyRatio, ACSEmployment]




acs_task, task_name, seed = folks[0], acss[0], param[0]
#pprint(inspect.getmembers(acs_task))
group_var = acs_task.group
target_var = acs_task.target
groups_to_keep = [1, 2]
acs_data = acs_data.loc[acs_data[group_var].isin(groups_to_keep)]
dataX, dataY, dataA = acs_task.df_to_pandas(acs_data)
# taking catoegorical features
definition_df = data_source.get_definitions(download=True)
categories = generate_categories(features=acs_task.group, definition_df=definition_df)
categories_cols = categories.keys()
# taking non-categorical features
# non_categorical_cols = [col for col in dataX.columns if col not in categories_cols]
# dataX[non_categorical_cols] = dataX[non_categorical_cols].astype(float)
# # use standard scaler to scale non_categorical_cols
# pipe = Pipeline([('scaler', StandardScaler())])
# dataX[non_categorical_cols] = pipe.fit_transform(dataX[non_categorical_cols])
# # use one-hot encoding to encode categorical_cols
# dataX = pd.get_dummies(dataX, columns=categories_cols)
# # process dataA and dataY
# columnsY = dataY.columns
# columnsA = dataA.columns
# #categorize dataA
# dataA = dataA.apply(lambda x: x.astype('category').cat.codes)
# dataY = dataY.apply(lambda x: x.astype('category').cat.codes)
# df = create_dataset_ref(dataX, dataA, dataY)
# # # create folder with task_name if not exist
# if not os.path.exists('{}'.format(task_name)):
#     os.makedirs('{}'.format(task_name))
# path = '{}/dataset_ref.csv'.format(task_name)
# df.to_csv(path, index=False)